server:
  port: 8080
  servlet:
    context-path: /hotel-booking

spring:
  application:
    name: hotel-booking-system

  security:
    user:
      name: admin
      password: 12345678

  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_booking_system"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
  jpa:
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pvlong1504@gmail.com
    password: fmof tmqw vhpf wqob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

vnpay:
  tmnCode: 9MASX4HI
  hashSecret: MITKX7R7KYM02X2K5G154TQ5GA29AEEC
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/hotel-booking/api/v1/payment/vnpay-return

jwt:
  signerKey: "a193e5f9c15cd8ce16e881b591e21f1a91bda4ea6a41313d4b24d07e5c466821"
  valid-duration: 3600 # Thời hạn token (giây)
  refreshable-duration: 36000 # Khoảng thời gian có thể refresh token (giây)