server:
  port: 8080
  #port: ${PORT:8080}
  servlet:
    context-path: /hotel-booking

spring:
  application:
    name: hotel-booking-system

  security:
    user:
      name: admin
      password: 12345678

  datasource:
    url: "jdbc:mysql://localhost:3306/hotel_booking_system?useSSL=false&serverTimezone=UTC"
    #url: jdbc:mysql://maglev.proxy.rlwy.net:18732/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #url: ${DB_URL}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
    #password: VdfFHcxwFibZomsQKYAAbWLbysdQyFsT
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: pvlong1504@gmail.com
    password: fmof tmqw vhpf wqob
    #username: ${MAIL_USERNAME}
    #password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000

  ai:
    # Check xem có model nào - GET https://generativelanguage.googleapis.com/v1beta/models?key=API_KEY
    openai:
      api-key: AIzaSyA6O3LqJlZy1TzV6vIaWs6xfe8G0oXFVeI
      #api-key: ${OPENAI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: models/gemini-3-flash-preview
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            platform: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG

vnpay:
  # Test: https://sandbox.vnpayment.vn/apis/vnpay-demo/
  tmnCode: 9MASX4HI
  hashSecret: MITKX7R7KYM02X2K5G154TQ5GA29AEEC
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/hotel-booking/api/v1/payments/vnpay-return
  #returnUrl: https://hotel-booking-system-aruze.onrender.com/hotel-booking/api/v1/payments/vnpay-return

jwt:
  signerKey: "a193e5f9c15cd8ce16e881b591e21f1a91bda4ea6a41313d4b24d07e5c466821"
  #signerKey: ${JWT_SECRET}
  valid-duration: 36000 # Thời hạn token (giây)
  refreshable-duration: 360000 # Khoảng thời gian có thể refresh token (giây)

cloudinary:
  cloud-name: duibxo3kw
  api-key: 885231218479346
  api-secret: I32nwhbrHOevdS1tjB8y4MwSs6k
  #cloud-name: ${CLOUDINARY_CLOUD_NAME}
  #api-key: ${CLOUDINARY_API_KEY}
  #api-secret: ${CLOUDINARY_API_SECRET}